/* tslint:disable */
/* eslint-disable */
/**
 * Medical Records API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MedicalAct
 */
export interface MedicalAct {
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    user_id?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    hospital_id?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    mutuelle_id?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    metadata1?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    metadata2?: string;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    montant_total?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    prise_en_charge_hopital?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    prise_en_charge_mutuelle?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    prise_en_charge_patient?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmation_paiement_patient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmation_mutuelle?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmation_rdv?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    pourcentage_prise_en_charge?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    commentaire?: string;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    date_creation?: string;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    date_prevue?: string;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    date_venue?: string;
}
