/* tslint:disable */
/* eslint-disable */
/**
 * Medical Records API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MedicalAct
 */
export interface MedicalAct {
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    hospitalId?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    mutuelleId?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    metadata1?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    metadata2?: string;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    montantTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    priseEnChargeHopital?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    priseEnChargeMutuelle?: number;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    priseEnChargePatient?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmationPaiementPatient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmationMutuelle?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MedicalAct
     */
    confirmationRdv?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MedicalAct
     */
    pourcentagePriseEnCharge?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicalAct
     */
    commentaire?: string;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    dateCreation?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    datePrevue?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MedicalAct
     */
    dateVenue?: Date;
}
