/* tslint:disable */
/* eslint-disable */
/**
 * Medical Records API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
import type { AxiosResponse, AxiosInstance, AxiosRequestConfig } from "axios";
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import type { Hospital } from '../models';
/**
 * HospitalApi - axios parameter creator
 * @export
 */
export const HospitalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of hospitals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hospitalGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/hospital`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hospitalIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling hospitalIdDelete.');
            }
            const localVarPath = `/hospital/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hospitalIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling hospitalIdGet.');
            }
            const localVarPath = `/hospital/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a hospital by ID
         * @param {Hospital} body 
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hospitalIdPut: async (body: Hospital, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling hospitalIdPut.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling hospitalIdPut.');
            }
            const localVarPath = `/hospital/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new hospital
         * @param {Hospital} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hospitalPost: async (body: Hospital, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling hospitalPost.');
            }
            const localVarPath = `/hospital`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HospitalApi - functional programming interface
 * @export
 */
export const HospitalApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of hospitals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Hospital>>>> {
            const localVarAxiosArgs = await HospitalApiAxiosParamCreator(configuration).hospitalGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await HospitalApiAxiosParamCreator(configuration).hospitalIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Hospital>>> {
            const localVarAxiosArgs = await HospitalApiAxiosParamCreator(configuration).hospitalIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update a hospital by ID
         * @param {Hospital} body 
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdPut(body: Hospital, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Hospital>>> {
            const localVarAxiosArgs = await HospitalApiAxiosParamCreator(configuration).hospitalIdPut(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a new hospital
         * @param {Hospital} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalPost(body: Hospital, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Hospital>>> {
            const localVarAxiosArgs = await HospitalApiAxiosParamCreator(configuration).hospitalPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HospitalApi - factory interface
 * @export
 */
export const HospitalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get a list of hospitals
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Hospital>>> {
            return HospitalApiFp(configuration).hospitalGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return HospitalApiFp(configuration).hospitalIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a hospital by ID
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Hospital>> {
            return HospitalApiFp(configuration).hospitalIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a hospital by ID
         * @param {Hospital} body 
         * @param {number} id Hopital id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalIdPut(body: Hospital, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Hospital>> {
            return HospitalApiFp(configuration).hospitalIdPut(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new hospital
         * @param {Hospital} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hospitalPost(body: Hospital, options?: AxiosRequestConfig): Promise<AxiosResponse<Hospital>> {
            return HospitalApiFp(configuration).hospitalPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HospitalApi - object-oriented interface
 * @export
 * @class HospitalApi
 * @extends {BaseAPI}
 */
export class HospitalApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of hospitals
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalApi
     */
    public async hospitalGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Hospital>>> {
        return HospitalApiFp(this.configuration).hospitalGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete a hospital by ID
     * @param {number} id Hopital id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalApi
     */
    public async hospitalIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return HospitalApiFp(this.configuration).hospitalIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a hospital by ID
     * @param {number} id Hopital id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalApi
     */
    public async hospitalIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Hospital>> {
        return HospitalApiFp(this.configuration).hospitalIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update a hospital by ID
     * @param {Hospital} body 
     * @param {number} id Hopital id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalApi
     */
    public async hospitalIdPut(body: Hospital, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Hospital>> {
        return HospitalApiFp(this.configuration).hospitalIdPut(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a new hospital
     * @param {Hospital} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalApi
     */
    public async hospitalPost(body: Hospital, options?: AxiosRequestConfig) : Promise<AxiosResponse<Hospital>> {
        return HospitalApiFp(this.configuration).hospitalPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
