/* tslint:disable */
/* eslint-disable */
/**
 * Medical Records API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
import type { AxiosResponse, AxiosInstance, AxiosRequestConfig } from "axios";
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import type { Mutuelle } from '../models';
/**
 * MutuelleApi - axios parameter creator
 * @export
 */
export const MutuelleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of mutuelles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mutuelleGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/mutuelle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mutuelleIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mutuelleIdDelete.');
            }
            const localVarPath = `/mutuelle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mutuelleIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mutuelleIdGet.');
            }
            const localVarPath = `/mutuelle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a mutuelle by ID
         * @param {Mutuelle} body 
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mutuelleIdPut: async (body: Mutuelle, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling mutuelleIdPut.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mutuelleIdPut.');
            }
            const localVarPath = `/mutuelle/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            //@ts-ignore
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new mutuelle
         * @param {Mutuelle} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mutuellePost: async (body: Mutuelle, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling mutuellePost.');
            }
            const localVarPath = `/mutuelle`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            //@ts-ignore
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MutuelleApi - functional programming interface
 * @export
 */
export const MutuelleApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a list of mutuelles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Mutuelle>>>> {
            const localVarAxiosArgs = await MutuelleApiAxiosParamCreator(configuration).mutuelleGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await MutuelleApiAxiosParamCreator(configuration).mutuelleIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Mutuelle>>> {
            const localVarAxiosArgs = await MutuelleApiAxiosParamCreator(configuration).mutuelleIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update a mutuelle by ID
         * @param {Mutuelle} body 
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdPut(body: Mutuelle, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Mutuelle>>> {
            const localVarAxiosArgs = await MutuelleApiAxiosParamCreator(configuration).mutuelleIdPut(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a new mutuelle
         * @param {Mutuelle} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuellePost(body: Mutuelle, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Mutuelle>>> {
            const localVarAxiosArgs = await MutuelleApiAxiosParamCreator(configuration).mutuellePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MutuelleApi - factory interface
 * @export
 */
export const MutuelleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get a list of mutuelles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Mutuelle>>> {
            return MutuelleApiFp(configuration).mutuelleGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return MutuelleApiFp(configuration).mutuelleIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a mutuelle by ID
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Mutuelle>> {
            return MutuelleApiFp(configuration).mutuelleIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a mutuelle by ID
         * @param {Mutuelle} body 
         * @param {number} id Mutuelle id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuelleIdPut(body: Mutuelle, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Mutuelle>> {
            return MutuelleApiFp(configuration).mutuelleIdPut(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new mutuelle
         * @param {Mutuelle} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mutuellePost(body: Mutuelle, options?: AxiosRequestConfig): Promise<AxiosResponse<Mutuelle>> {
            return MutuelleApiFp(configuration).mutuellePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MutuelleApi - object-oriented interface
 * @export
 * @class MutuelleApi
 * @extends {BaseAPI}
 */
export class MutuelleApi extends BaseAPI {
    /**
     * 
     * @summary Get a list of mutuelles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MutuelleApi
     */
    public async mutuelleGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Mutuelle>>> {
        return MutuelleApiFp(this.configuration).mutuelleGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete a mutuelle by ID
     * @param {number} id Mutuelle id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MutuelleApi
     */
    public async mutuelleIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return MutuelleApiFp(this.configuration).mutuelleIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a mutuelle by ID
     * @param {number} id Mutuelle id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MutuelleApi
     */
    public async mutuelleIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Mutuelle>> {
        return MutuelleApiFp(this.configuration).mutuelleIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update a mutuelle by ID
     * @param {Mutuelle} body 
     * @param {number} id Mutuelle id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MutuelleApi
     */
    public async mutuelleIdPut(body: Mutuelle, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Mutuelle>> {
        return MutuelleApiFp(this.configuration).mutuelleIdPut(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a new mutuelle
     * @param {Mutuelle} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MutuelleApi
     */
    public async mutuellePost(body: Mutuelle, options?: AxiosRequestConfig) : Promise<AxiosResponse<Mutuelle>> {
        return MutuelleApiFp(this.configuration).mutuellePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
